### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jernejbanevec** [ZavbiA/Iskalnik-postnih-posiljk#1]
Pozdrav!
Pregledal sem vaš ER diagram in imam naslednje predloge:
* _id_ entitete _OSEBA_ naj bo kar **emšo** osebe, ki je potem kar primaren ključ,
* vsaka pošiljka iz entitete _POŠILJKA_ ima najbrž tudi enega samega pošiljatelja (torej se označi z odebeljeno puščico, kot ste to naredili pri prejemniku) in se (najbrž) nahaja na enem samem mestu,
* atribut _datum_ ne spada k entiteti _POŠTA_ (tu je namreč le poštna številka in kraj), temveč se ga lahko napiše kar k relaciji _se nahaja_ (tu bi bilo potem v primeru, če ste imeli plan beležiti celotno pot pošiljke z vmesnimi postajami, bolj smiselno imeti šibko entiteto _NAHAJALIŠČE_ s primarnim ključem _id pošiljke_, _poštna številka_ kraja in _datum_ (vključno z uro), ko je pošiljka prispela na ta kraj),
* entiteti _OSEBA_ in _POŠTA_ bi bilo smiselno povezati z relacijo. Tu ima oseba le atribut naslov (to je najbrž mišljeno kot ulica in hišna številka), manjka pa podatek o kraju (te bi se lahko preko poštne številka povezalo z entiteto _POŠTA_, od koder dobimo še informacijo o kraju).

Zanima me tudi ali ste nameravali kar predpostaviti da je pošiljka dostavljena prejemniku takrat, ko je pošiljka v kraju s poštno številko prejemnika ali ste nameravali to kako drugače beležiti?

**Comment by ZavbiA** [comment]
Živjo, smo popravile ER diagram. Je zdaj v redu? Edino pri nahajališču nismo sigurne.

**Comment by jernejbanevec** [comment]
Živjo, se opravičujem za poznejši odgovor. Iz _NAHAJALIŠČE_ bi odstranil _id pošiljke_, ki pride že iz relacije _se nahaja_, namesto črtkane črte pa bi bila tu še bolj smiselna uporaba odebeljene črte (okoli *NAHAJALIŠČE* in obeh relacij, vezanih na to šibko entiteto), so pa to malenkosti, tako da se mi zdi ER diagram ustrezen.
