### ISSUE TITLE
Tabele

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/Iskalnik-postnih-posiljk#2]
V datoteki uvoz.r imamo težave s pretvorbami stolpcev v tip date in numeric.
V tabeli posiljke je potrebno pretvoriti stolpca datum_postaja in datum_prispe v tip date. V tabeli oseba je potrebno pretvoriti stolpca uporabnisko_ime in telefonska v tip numeric.

**Comment by jernejbanevec** [comment]
Za pretvarjanje stolpcev v tip _numeric_, priporočam da uporabljate funkcijo [`parse_number`](https://www.rdocumentation.org/packages/readr/versions/1.3.1/topics/parse_number), za pretvorbo v tip _date_ (oziroma v primerih, ko imate poleg še uro, v tip _datetime_) pa funkcijo [`parse_date`](https://www.rdocumentation.org/packages/readr/versions/1.3.1/topics/parse_datetime) (oziroma `parse_datetime`). Vse funkcije so iz knjižice `readr`. Pretvorbo lahko naredite na sledeči način:
```R
library(readr)
posiljke$datum_oddaje <- parse_date(posiljke$datum_oddaje, format = "%m/%d/%Y")
posiljke$datum_prispe <- parse_datetime(posiljke$datum_prispe, format = "%m/%d/%Y %I:%M %p")
posiljke$vmesna_postaja <- parse_datetime(posiljke$vmesna_postaja, format = "%m/%d/%Y %I:%M %p")
```
Pri stolpcih `uporabnisko_ime` in `telefonska` pa je potrebno iz stolpcev najprej odstraniti znake "-", kar lahko storite s funkcijo `gsub`, nato pa to šele pretvoriti v številko:
```R
osebe$uporabnisko_ime <- gsub("-", "", osebe$uporabnisko_ime) %>% parse_number()
osebe$telefonska <- gsub("-", "", osebe$telefonska) %>% parse_number()
```
Svetujem, da to naredite že pred vrstico https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/d5cecfe94ebf1d93dbd0b8e6e72f5101847b201f/uvoz.R#L24 

Opazil pa sem tudi, da v tabelo _oseba_ shranjujete kar prava gesla uporabnikov. Običajno se shranjuje t.i. _hash_  oziroma gesla, na katerih se uporabi kodirna funkcija (za ta šolski primer se lahko uporabi kar [_MD5_](https://en.wikipedia.org/wiki/MD5), čeprav je ta v praksi že neuporaben, saj že obstaja "inverzna" funkcija).

**Comment by ZavbiA** [comment]
Hvala, zdaj je urejeno. Pri stolpcih datumov sicer zdaj piše, da so unknown, ampak so se spremenili in sklepam, da je to v redu.
Hvala še za opombo glede gesel, bomo tudi to uredile.
