### ISSUE TITLE
Funkcija za uporabnisko ime in geslo

### ISSUE THREAD

**Issue by ajdastare** [ZavbiA/Iskalnik-postnih-posiljk#3]
Pozdravljeni!

V shiny/server.R je napisana funkcija _probi.upor.ime.geslo_ ki za vneseno uporabnisko ime najde v bazi geslo. Zamislile smo si nekako tako, da bi potem to funkcijo uporabili v _sign.in.user_ , ki bi preverila če je to geslo pravo. Težavo imamo v tem da nekako ne dobimo z unlist funkcijo v _probi.upor.ime.geslo_ oziroma ne dobimo samo ene vrednosti. 

Zanima me, kako bi potem ko je uspesen sign.in tudi prišli na novo začetno stran ki bi imela samo razpredelnico pošiljk in ki bi se osveževala glede na to ali izbere uporabnik tiste pošiljke ki jih je oddal, oziroma želi videti tiste ki jih bi prejel. Zaenkrat je v _ui.R_  definiran samo conditionalPanel ki bi se prikazal samo po uspešnem sign in-u.
Razmišljale smo da je spodnja funkcija nekako za uvoz pošiljk, in bi se glede na to osvežili podatki:
uvoz_posiljk <- function(username){
    q_datum_oddaje_posiljatelj <- dbGetQuery("SELECT datum_oddaje FROM posiljke WHERE posiljatelj =", username,con = conn)
    q_datum_prispe_posiljatelj <- dbGetQuery("SELECT datum_oddaje FROM posiljke WHERE naslovnik =", username,con = conn)
  }

Hvala in lep pozdrav.

**Comment by jernejbanevec** [comment]
Zdravo, 
trenutno mi `uvoz.R` in `povezava.R` ne delujeta. Napako vidim na primer v https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/15ac534bfe62e5b961a2954ea9e14fd42e6abd70/povezava.R#L45-L52
tebela `osebe` ne vsebuje stolpca `geslo`, katerega potem vnesemo v to tabelo. Nekje so tudi napačna poimenovanja tabel, npr. `osebe` in `oseba` sta pogosto zamešana. Zni se mi tudi, da bi v https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/15ac534bfe62e5b961a2954ea9e14fd42e6abd70/povezava.R#L55 stolpec `postna_stevilka` moral biti `PRIMARY KEY`, tu pa se sklicuje na tabelo `oseba`. Ali ste prepričani, da je na github naložena zadnja verzija?

**Comment by ajdastare** [comment]
Zdravo!

Smo popravile povezava.R. 
Sedaj bi se moral shiny pognati. Probala sem se prijaviti uporabniskim imenom in geslom in ne  delaluje. Pri server/R sign.in.user je funkcija, ki filtrira  userTable %>% filter(uporabnisko_ime == uporabnik)  ... ko probam to uporabiti na tabeli osebe z nekim uporabniskim imenom mi ne vrne ničesar, tako da se mi zdi da je to problem.
