### ISSUE TITLE
Prikazovanje tabel po vpisu

### ISSUE THREAD

**Issue by ajdastare** [ZavbiA/Iskalnik-postnih-posiljk#4]
Zdravo! 

Sedaj sign-in dela npr. z:
uporabnisko ime:129912621, 
geslo:f06d6a2cf40838817b278735534defd4 ,
bi se moral uspešno vpisati.

Problem je le še v tem, da ne prikaže podatkov in ne vem zakaj. Ne vem tudi čist točno če je vredu definiran userID v server.R , kot reactiveVal(), in da vrne pravo vrednost. 

Hvala in lep pozdrav.

**Comment by ajdastare** [comment]
![Screen Shot 2019-08-02 at 11 20 06](https://user-images.githubusercontent.com/23086220/62359688-99c1c900-b517-11e9-86fb-69f7ddc59a99.png)
Našla sem podobno napako na spletu, samo ne razumem točno kaj je treba popraviti v kodi. [https://community.rstudio.com/t/dbplyr-dplyr-filter-worked-fine-in-r-3-5-1-but-fails-in-r-3-6-0-using-in-in-database-query/31664]

**Comment by jernejbanevec** [comment]
Napako pri izpisu `output$oddane.posiljke` sem odkril v https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/809318237ff5af68b56c6fbc0742111be3b9b6b4/shiny/ui.R#L73
Namesto `tableOutput` uporabite `DT::dataTableOutput`. V kolikor želite, v https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/809318237ff5af68b56c6fbc0742111be3b9b6b4/shiny/server.R#L137-L143 lahko poenotite izpis datumov, npr. tako, da dopišete 
```R
oddane_posiljke_data$`Datum prispetja` <- as.Date(as.POSIXct(oddane_posiljke_data$`Datum prispetja`))
```
in tako so potem vsi datumi samo v obliki datuma.

Tabela, ki se nato izpiše izgleda prazna, vendar je pisava, najbrž zarati izbire teme, bela (sam sem iskal napako v izpisu tabele). To lahko popravite, tako da v https://github.com/ZavbiA/Iskalnik-postnih-posiljk/blob/809318237ff5af68b56c6fbc0742111be3b9b6b4/shiny/server.R#L147 dopišete na konec še 
```R
%>% DT::formatStyle(columns = c('Datum oddaje', 'Datum prispetja'), color = 'black')
```
Enako je tudi pri `output$prejete.posiljke`. A to reši problem ali sem narobe razumel napako? 

Sicer pa poskusite vpis urediti tako, da se uporabnik ne vpisuje neposredno s hashom, vendar naj se vpiše v svojim prvotnim geslom in nato to geslo "hashirajte" in primerjajte če je hash gesla shranjen v tabeli.

Opazil sem pa tudi, da so podatki slabi in tabele niso dobro sestavljene (tudi SQL stavki za sestavo tabel so slabo sestavljeni), saj se na primer v tabeli `posiljke` večkrat ponovi določen `ID`, ta pa posledično ni *PRIMARY KEY*, čeprav bi to moral biti. Podobne napake sem opazil tudi v kakšni drugi tabeli.

**Comment by ZavbiA** [comment]
Popravile smo datoteke, vezane na sql bazo. Izbrisale smo datoteko povezave.R in ustvarile datoteke sql.r, vstavljanje.R in brisanje.R. Prej smo imele problem, da so se tabele večkrat naložile na sql (kot da bi se podvajale). Zato so bile težave s primary key. Zdaj nam javlja naslednjo napako: 
![problem_conn](https://user-images.githubusercontent.com/26707449/62476356-1b7b5600-b7a7-11e9-9997-ee6da9a2a1e0.png)

V čem je zdaj problem?
Hvala za zgornje opombe, bomo popravile še gesla.

**Comment by ajdastare** [comment]
Ugotovila sem, da je to problem pri paketu dbplyr. Potrebno je naložiti starejšo verzijo. To naredita tako:
packageurl <- https://cran.r-project.org/src/contrib/Archive/dbplyr/dbplyr_1.2.1.tar.gz
install.packages(packageurl, repos=NULL, type="source")

Upam da vama bo delalo. Sedaj se lepo pobrišejo tabele in naredijo nove. Problem je le še pri vstavljanju podatkov, kar pa popravljam. :)

**Comment by ZavbiA** [comment]
Pri meni to ne reši problema, ker se mi stalno pojavlja to obvestilo:

![problem_1](https://user-images.githubusercontent.com/26707449/62677112-6797e780-b9ad-11e9-9b7e-074f9eea5e0c.png)

**Comment by jaanos** [comment]
Pristop nameščanja starejših različic paketov ni najbolj priporočljiv - raje priredite kodo tako, da bo delovala z najnovejšo različico.

V vašem primeru bi moralo zadostovati, če pri vseh uporabah funkcije `build_sql` podaste še parameter `con=conn` (glejte timotejvesel/vojne#1) - kolikor vidim, tega ne počnete v `sql.r` in `brisanje.R`.

**Comment by ZavbiA** [comment]
Hvala, to je rešilo problem s conn. Še vedno pa nam javlja napako "...could not translate host name...". Ali morda veste, zakaj pride do tega?
Pred tem vedno odpre sledeče:
![okence](https://user-images.githubusercontent.com/26707449/62710090-eebd7d80-b9f6-11e9-9e1f-e21170a47ab8.png)

**Comment by ZavbiA** [comment]
Vpisovanje z originalnimi gesli in prevajanjem na hash gesla je zdaj urejeno.
Vpišemo se lahko npr. z uporabniškim imenom 129912621.0 in geslom ryGI1jZtKq

**Comment by jaanos** [comment]
Za zgornjo napako nisem prepričan, zakaj pride do nje - kolikor sem gledal, lahko pride do tega pri nadgradnji sistema. @ZavbiA, ali se ta napaka še vedno pojavlja? Sta tudi @ajdastare in @spelaognjanovic naleteli nanjo?

Prijava z navedenim uporabniškim imenom in geslom pri meni ne deluje - pravzaprav pride do napake, saj ne najde funkcije `digest`. Sam sem poskusil naložiti še knjižnico `digest`, ki ni naložena - sklepam, da uporabljate to funkcijo (lahko v konzolo napišete `digest`, pa bo med predlogi zraven imena funkcije s sivo v zavitih oklepajih napisalo še knjižnico, iz katere pride funkcija).

Ali je sploh smiselno, da so uporabniška imena (decimalne) številke? Svetujem, da imate namesto tega stolpec `id` tipa `SERIAL` (ali pa `INTEGER`, če ga same generirate) - ta naj bo glavni ključ, nanj pa nastavite ustrezne tuje ključe - in pa še uporabniško ime tipa `TEXT` z dejanskimi uporabniškimi imeni (nanj dajte omejitev `UNIQUE`, da se ne bodo ponavljala). Če podatke generirate z [Mockaroo](https://mockaroo.com/)jem, potem lahko izberete *Username* za tip stolpca, pa se bodo generirana uporabniška imena skladala z imeni in priimki (mimogrede lahko generirate še telefonske številke, da bodo izgledale realistične).

Mimogrede, v `ui.R` kličete `libraries.r`, a ima program v mapi `lib` končnico `.R` (velika črka!), tako da to popravite. Prav tako bo treba v `server.R` klicati še `auth_public.R`, da se lahko povežete na bazo.

**Comment by ZavbiA** [comment]
Ta napaka se še vedno pojavlja, načeloma jo uspem odpraviti, če vsakič, ko na novo odprem R, instaliram paket "dbplyr" in dodam, kar je @ajdastare zapisala (starejša verzija), ampak to najbrž ni dobra rešitev problema. @spelaognjanovic ima isti problem, @ajdastare  pa nima težav.

Uporabljamo knjižnico digest, bomo dodale še ukaz library(digest).

Hvala za vsa opozorila, bomo poskusile še danes ali jutri odpraviti napake.
