### ISSUE TITLE
Error v shinyju

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/Iskalnik-postnih-posiljk#5]
Pozdravljeni!

Zdaj nam aplikacija že kar dobro deluje, imamo pa še dve težavi:
- v Shiny aplikaciji se pojavlja Error: no applicable method for 'escape' applied to an object of class "c('reactiveVal', 'reactive')"
- Sporočilo nam ne deluje pravilno. Če kaj vpišemo, se okence aplikacije zapre, vseeno pa se v R-u ne ustavi. Na sql bazo sporočilo ni poslano, čeprav bi se moralo zabeležiti v tabeli sporočilo.

Prosimo za pomoč.

**Comment by jaanos** [comment]
Kolikor vidim, na več mestih uporabljate samo `userID` namesto `userID()` (tudi pri dodajanju sporočila) - od tod prva napaka.

Sam sicer na začetku dobim še napako zaradi nepravilnega stavka SQL, ki izvira iz tega, da `userID()` na začetku ni nastavljen. Da se temu izognete, lahko pripravite izraz, ki bo poskrbel za prekinitev izvajanja, če uporabnik ni prijavljen:
```R
  uporabnik <- reactive({
    user <- userID()
    validate(need(!is.null(user), "Potrebna je prijava!"))
    user
  })
```
Tako lahko namesto `userID()` uporabljate `uporabnik()` - če uporabnik ob tem ni prijavljen, se npr. ne bo izvedel nepopoln stavek SQL, pač pa se bo na mesto ustreznega gradnika prikazalo podano sporočilo.

Še to: da bo delovalo dodajanje sporočil, boste morale uporabniku `javnost` dati pravico `INSERT` na tabeli `sporocilo`.
